### ISSUE TITLE
preprocessing scripts incomplete?

### ISSUE THREAD

**Issue by dhetting** [sustainlab-group/africa_poverty#2]
I've successfully run the first step to download the raw TFRecords from Earth Engine, but it looks like there's a gap between the first download script and the preprocessing. My filenames are all named according to a single country, single year, and chunk number, but it looks like `process_tf_records_dhs.ipynb` expects combined files for a single country with the name format `lx_median_{year_range}_{country}_dhslocs_ee_export.tfrecord.gz`. I don't see anywhere in the repo to create these; is there a missing preprocessing step?

**Comment by chrisyeh96** [comment]
Hi @dhetting , this repo is still a work in progress. In the meantime, please check out [chrisyeh96/africa_poverty_clean](https://github.com/chrisyeh96/africa_poverty_clean/) which has more up-to-date preprocessing code. Eventually I aim to port that repo over to this one.

**Comment by dhetting** [comment]
Thanks, I’ll work with that repo
