### ISSUE TITLE
license and reproducibility 

### ISSUE THREAD

**Issue by GaelKBertrand** [sustainlab-group/africa_poverty#6]
I realised license is not specifically mentioned in this project. I am running a similar project where I would need to directly re-use some of the code scripts as exactly as they are, especially the data pre-processing part. I would like to understand if there something I can know regarding the permission to use the code scripts and citing.

**Comment by chrisyeh96** [comment]
I added the MIT License (commit 653ed5a60). Feel free to copy the scripts for your own use, and please cite us as appropriate.
